replicaCount: 1
image:
  vote:
    repository: 878445923420.dkr.ecr.us-east-1.amazonaws.com/vote
    tag: c4d18fefee2aab87ec15920c235638050a747a62
    pullPolicy: Always
  result:
    repository: 878445923420.dkr.ecr.us-east-1.amazonaws.com/result
    tag: c4d18fefee2aab87ec15920c235638050a747a62
    pullPolicy: Always
  worker:
    repository: 878445923420.dkr.ecr.us-east-1.amazonaws.com/worker
    tag: c4d18fefee2aab87ec15920c235638050a747a62
    pullPolicy: Always
  redis:
    repository: redis
    tag: "7.2"
    pullPolicy: IfNotPresent
  postgres:
    repository: postgres
    tag: "16"
    pullPolicy: IfNotPresent
service:
  vote:
    type: ClusterIP
    port: 80
  result:
    type: ClusterIP
    port: 80
  redis:
    type: ClusterIP
    port: 6379
  postgres:
    type: ClusterIP
    port: 5432
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: voting.local
      paths:
        - path: /
          pathType: Prefix
          backendService: vote
          backendPort: 80
        - path: /result
          pathType: Prefix
          backendService: result
          backendPort: 80
  tls: []
