service:
  vote:
    type: ClusterIP
    port: 80
  result:
    type: ClusterIP
    port: 80
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: voting.local
      paths:
        - path: /
          pathType: Prefix
          backendService: vote
          backendPort: 80
        - path: /result
          pathType: Prefix
          backendService: result
          backendPort: 80
  tls: []
image:
  vote:
    tag: 456ea61da12954a75c4769a2b6c969a329723756
  worker:
    tag: 456ea61da12954a75c4769a2b6c969a329723756
  result:
    tag: 456ea61da12954a75c4769a2b6c969a329723756
