apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-vote
  labels:
    app: vote
spec:
  type: {{ .Values.service.vote.type }}
  ports:
    - port: {{ .Values.service.vote.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: vote
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-result
  labels:
    app: result
spec:
  type: {{ .Values.service.result.type }}
  ports:
    - port: {{ .Values.service.result.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: result
